sonar.organization=good-burguer
sonar.projectKey=good-burguer_lanchonete-orchestrator
sonar.projectName=lanchonete-orchestrator

# Código-fonte
sonar.sources=app

# Testes
sonar.tests=tests
sonar.test.inclusions=tests/**

# Cobertura (pytest-cov -> coverage.xml na raiz)
sonar.python.coverage.reportPaths=coverage.xml

# Versão do Python usada para análise
sonar.python.version=3.12

# Excluir arquivos irrelevantes
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/.venv/**
